---

- name: " (10) Check existence of the JBoss FUSE installation"
  become: true
  stat:
    path: "{{ fuse_home + '/readme.txt'}}"
  register: jboss_fuse_exists


- name: " (10) Copy zipped JBoss FUSE distribution to ({{ download_dir }})"
  become: true
  copy:
    src: "{{ local_rh_bin_dir }}/{{ jboss_fuse_zip }}"
    dest: "{{ download_dir }}"
    owner: "{{ fuse.user }}"
    group: "{{ fuse.group }}"
  register: copy_zip_state

# This command fails with ansible 2.1.0.0
- name: " (10) Extract JBoss FUSE zipped distribution to ({{ fuse.user_home }})"
  become: true
  # new version or no installation so far
  when: jboss_fuse_exists.stat.exists == false or copy_zip_state.changed == true
  unarchive:
    src: "{{ download_dir }}/{{ jboss_fuse_zip }}"
    dest: "{{ fuse.user_home }}"
    copy: false
    owner: "{{ fuse.user }}"
    group: "{{ fuse.group }}"
  register: distribution

